title:              Grupa građana Raša
email:              marko.milic@yahoo.com
description:        Internet portal Grupa građana Raša
author:             Marko Milić
baseurl:            "/"
url:                "https://www.karlovackih-vinogradara.site"

# Social Profiles
twitter_username:   milic_marko
github_username:    constantine2nd
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
